language: php

"os": [
    "linux"
],
"dist": "precise"

php:
  - 8.0.12

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --verbose
